{% set name = "enaml-extensions" %}
{% set version = "0.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enaml-extensions-{{ version }}.tar.gz
  sha256: cf2fd8373fa24102c349c176de237c6c4061b7c259833f67a250d80a477dff1d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - enaml
    - numpy
    - pip
    - python >={{ python_min }}
    - qscintilla2
    - qtpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - enamlext

about:
  home: http://github.com/gabrielcnr/enaml-extensions
  summary: Extra widgets and extensions for building UIs with Enaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
