{% set name = "enaml-extensions" %}
{% set version = "0.4.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 86c3047180379c7c2aa54eb0ab09fb6af4748d16120bbac1c10d7d31c58580af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - enaml
    - numpy
    - pip
    - python >={{ python_min }}
    - qscintilla2
    - qtpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - enamlext

about:
  home: http://github.com/gabrielcnr/enaml-extensions
  summary: Extra widgets and extensions for building UIs with Enaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
